"""Move position_id from Member to TeamMember

Revision ID: 0fc65e842da3
Revises: f32da16dc0cb
Create Date: 2026-02-02 12:41:33.189796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fc65e842da3'
down_revision: Union[str, None] = 'f32da16dc0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('member_position_id_fkey'), 'member', schema='core', type_='foreignkey')
    op.drop_column('member', 'position_id', schema='core')
    op.add_column('team_member', sa.Column('position_id', sa.Uuid(), nullable=True), schema='core')
    op.create_foreign_key(None, 'team_member', 'player_position', ['position_id'], ['id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_member', schema='core', type_='foreignkey')
    op.drop_column('team_member', 'position_id', schema='core')
    op.add_column('member', sa.Column('position_id', sa.UUID(), autoincrement=False, nullable=True), schema='core')
    op.create_foreign_key(op.f('member_position_id_fkey'), 'member', 'player_position', ['position_id'], ['id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###
