"""Add journee to Game

Revision ID: 28c2379ad64c
Revises: 4c08cceb4bcb
Create Date: 2026-01-24 23:54:43.780016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28c2379ad64c'
down_revision: Union[str, None] = '4c08cceb4bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('journee', sa.Integer(), nullable=True), schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'journee', schema='reference')
    # ### end Alembic commands ###
