"""Add administrative fields to member

Revision ID: 363316b500f9
Revises: 1f2f3aebb684
Create Date: 2026-02-10 21:27:52.376246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '363316b500f9'
down_revision: Union[str, None] = '1f2f3aebb684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('medical_certificate_date', sa.Date(), nullable=True), schema='core')
    op.add_column('member', sa.Column('contribution_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True), schema='core')
    op.add_column('member', sa.Column('clothing_size', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'clothing_size', schema='core')
    op.drop_column('member', 'contribution_status', schema='core')
    op.drop_column('member', 'medical_certificate_date', schema='core')
    # ### end Alembic commands ###
