"""move_position_id_to_member

Revision ID: 3d12da5434dd
Revises: 28c2379ad64c
Create Date: 2026-01-27 07:55:00.948313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d12da5434dd'
down_revision: Union[str, None] = '28c2379ad64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS sport.formation_position")
    op.execute("DROP TABLE IF EXISTS sport.formation")
    op.execute("DROP TABLE IF EXISTS core.formation_position")
    op.execute("DROP TABLE IF EXISTS core.match_lineup")
    op.execute("DROP TABLE IF EXISTS core.formation")
    op.add_column('member', sa.Column('position_id', sa.Uuid(), nullable=True), schema='core')
    op.create_foreign_key(None, 'member', 'player_position', ['position_id'], ['id'], source_schema='core', referent_schema='core')
    op.drop_constraint(op.f('team_member_position_id_fkey'), 'team_member', schema='core', type_='foreignkey')
    op.drop_column('team_member', 'position_id', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('position_id', sa.UUID(), autoincrement=False, nullable=True), schema='core')
    op.create_foreign_key(op.f('team_member_position_id_fkey'), 'team_member', 'player_position', ['position_id'], ['id'], source_schema='core', referent_schema='core')
    op.drop_constraint(None, 'member', schema='core', type_='foreignkey')
    op.drop_column('member', 'position_id', schema='core')
    op.create_table('formation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('formation_pkey')),
    schema='core'
    )
    op.create_table('match_lineup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('formation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['core.event.id'], name=op.f('match_lineup_event_id_fkey')),
    sa.ForeignKeyConstraint(['member_id'], ['core.member.id'], name=op.f('match_lineup_member_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], name=op.f('match_lineup_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('match_lineup_pkey')),
    schema='core'
    )
    op.create_table('formation_position',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('coord_x', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('coord_y', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('position_label', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['core.formation.id'], name=op.f('formation_position_formation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('formation_position_pkey')),
    sa.UniqueConstraint('formation_id', 'coord_x', 'coord_y', name=op.f('formation_position_formation_id_coord_x_coord_y_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='core'
    )
    op.create_table('formation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('formation_pkey')),
    schema='sport'
    )
    op.create_table('formation_position',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('coord_x', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('coord_y', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('position_label', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['sport.formation.id'], name=op.f('formation_position_formation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('formation_position_pkey')),
    sa.UniqueConstraint('formation_id', 'coord_x', 'coord_y', name=op.f('formation_position_formation_id_coord_x_coord_y_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='sport'
    )
    # ### end Alembic commands ###
