"""add_real_club_id_to_tenant

Revision ID: 4c08cceb4bcb
Revises: e5104d425da0
Create Date: 2026-01-24 11:35:53.351028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c08cceb4bcb'
down_revision: Union[str, None] = 'e5104d425da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('real_club_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='saas')
    op.create_index(op.f('ix_saas_tenant_real_club_id'), 'tenant', ['real_club_id'], unique=True, schema='saas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saas_tenant_real_club_id'), table_name='tenant', schema='saas')
    op.drop_column('tenant', 'real_club_id', schema='saas')
    # ### end Alembic commands ###
