"""create_match_lineup_table

Revision ID: 6ca07c50d58e
Revises: 3d12da5434dd
Create Date: 2026-01-27 12:20:01.920513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ca07c50d58e'
down_revision: Union[str, None] = '3d12da5434dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS core.match_lineup")
    op.execute("DROP TABLE IF EXISTS core.formation_position")
    op.execute("DROP TABLE IF EXISTS core.formation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('formation_pkey')),
    schema='core'
    )
    op.create_table('formation_position',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('coord_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('coord_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('position_label', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['core.formation.id'], name=op.f('formation_position_formation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('formation_position_pkey')),
    sa.UniqueConstraint('formation_id', 'coord_x', 'coord_y', name=op.f('uq_fmt_pos_coords'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='core'
    )
    op.create_table('match_lineup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('formation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['core.event.id'], name=op.f('match_lineup_event_id_fkey')),
    sa.ForeignKeyConstraint(['formation_id'], ['core.formation.id'], name=op.f('match_lineup_formation_id_fkey')),
    sa.ForeignKeyConstraint(['member_id'], ['core.member.id'], name=op.f('match_lineup_member_id_fkey')),
    sa.ForeignKeyConstraint(['position_id'], ['core.formation_position.id'], name=op.f('match_lineup_position_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], name=op.f('match_lineup_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('match_lineup_pkey')),
    schema='core'
    )
    # ### end Alembic commands ###
