"""restore_sport_tables

Revision ID: 8e2a65bc76fe
Revises: 6ca07c50d58e
Create Date: 2026-01-27 12:25:38.224546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e2a65bc76fe'
down_revision: Union[str, None] = '6ca07c50d58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
