"""replace_game_constraint_with_hash

Revision ID: 8ebf8d877573
Revises: 8e2a65bc76fe
Create Date: 2026-02-01 20:29:41.145595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ebf8d877573'
down_revision: Union[str, None] = '8e2a65bc76fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE reference.game DROP CONSTRAINT IF EXISTS uq_game_details")
    op.create_unique_constraint('uq_game_data_hash', 'game', ['data_hash'], schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_game_data_hash', 'game', schema='reference', type_='unique')
    op.create_unique_constraint(op.f('uq_game_details'), 'game', ['competition_id', 'home_team_name', 'away_team_name', 'season', 'date_match', 'date_time'], schema='reference', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
