"""initial_init

Revision ID: 9458bee1bfec
Revises: 
Create Date: 2026-01-23 21:49:51.798367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9458bee1bfec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS reference")
    op.execute("CREATE SCHEMA IF NOT EXISTS saas")
    op.execute("CREATE SCHEMA IF NOT EXISTS sport")
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('game_action_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('game_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('member_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('participation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('player_position',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('task_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IMPORT', 'UPDATE', name='jobtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('configs', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('federation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('real_federation_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('fff_all_clubs',
    sa.Column('cl_no', sa.Integer(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('cl_no'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_fff_all_clubs_cl_no'), 'fff_all_clubs', ['cl_no'], unique=False, schema='reference')
    op.create_table('season',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    schema='reference'
    )
    op.create_table('plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('stripe_price_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='saas'
    )
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stripe_customer_id'),
    schema='saas'
    )
    op.create_index(op.f('ix_saas_tenant_slug'), 'tenant', ['slug'], unique=True, schema='saas')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    schema='saas'
    )
    op.create_index(op.f('ix_saas_users_email'), 'users', ['email'], unique=True, schema='saas')
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.ForeignKeyConstraint(['type'], ['core.event_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('role_in_app', sa.Uuid(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['role_in_app'], ['core.member_role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['saas.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('league',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('real_league_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('federation_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['reference.federation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_league_id'),
    schema='reference'
    )
    op.create_table('team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['season'], ['reference.season.name'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['saas.plan.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    schema='saas'
    )
    op.create_table('event_participation',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['core.event.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['core.member.id'], ),
    sa.ForeignKeyConstraint(['status'], ['core.participation_status.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'member_id'),
    schema='core'
    )
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('assigned_member_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_member_id'], ['core.member.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['core.event.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['core.task_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('team_member',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('strong_foot', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['core.member.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['core.player_position.id'], ),
    sa.ForeignKeyConstraint(['season'], ['reference.season.name'], ),
    sa.ForeignKeyConstraint(['team_id'], ['reference.team.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'member_id'),
    schema='core'
    )
    op.create_table('club',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('real_club_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('league_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('zipcode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affiliation_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['reference.league.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_club_id'),
    schema='reference'
    )
    op.create_table('competition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('real_competition_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('league_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['reference.league.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('home_team_id', sa.Uuid(), nullable=True),
    sa.Column('home_team_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('home_penalty_score', sa.Integer(), nullable=True),
    sa.Column('home_is_forfeit', sa.Boolean(), nullable=True),
    sa.Column('away_team_id', sa.Uuid(), nullable=True),
    sa.Column('away_team_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('away_penalty_score', sa.Integer(), nullable=True),
    sa.Column('away_is_forfeit', sa.Boolean(), nullable=True),
    sa.Column('date_match', sa.Date(), nullable=True),
    sa.Column('date_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('seems_postponed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('data_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('stadium', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['reference.team.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['reference.competition.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['reference.team.id'], ),
    sa.ForeignKeyConstraint(['season'], ['reference.season.name'], ),
    sa.ForeignKeyConstraint(['status'], ['core.game_status.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('game_timeline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('main_home_player_id', sa.Uuid(), nullable=True),
    sa.Column('assisting_home_player_id', sa.Uuid(), nullable=True),
    sa.Column('main_away_player_id', sa.Uuid(), nullable=True),
    sa.Column('assisting_away_player_id', sa.Uuid(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['core.game_action_type.id'], ),
    sa.ForeignKeyConstraint(['assisting_away_player_id'], ['core.member.id'], ),
    sa.ForeignKeyConstraint(['assisting_home_player_id'], ['core.member.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['reference.game.id'], ),
    sa.ForeignKeyConstraint(['main_away_player_id'], ['core.member.id'], ),
    sa.ForeignKeyConstraint(['main_home_player_id'], ['core.member.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['saas.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_timeline', schema='core')
    op.drop_table('game', schema='reference')
    op.drop_table('competition', schema='reference')
    op.drop_table('club', schema='reference')
    op.drop_table('team_member', schema='core')
    op.drop_table('task', schema='core')
    op.drop_table('event_participation', schema='core')
    op.drop_table('subscription', schema='saas')
    op.drop_table('team', schema='reference')
    op.drop_table('league', schema='reference')
    op.drop_table('member', schema='core')
    op.drop_table('event', schema='core')
    op.drop_index(op.f('ix_saas_users_email'), table_name='users', schema='saas')
    op.drop_table('users', schema='saas')
    op.drop_index(op.f('ix_saas_tenant_slug'), table_name='tenant', schema='saas')
    op.drop_table('tenant', schema='saas')
    op.drop_table('plan', schema='saas')
    op.drop_table('season', schema='reference')
    op.drop_index(op.f('ix_reference_fff_all_clubs_cl_no'), table_name='fff_all_clubs', schema='reference')
    op.drop_table('fff_all_clubs', schema='reference')
    op.drop_table('federation', schema='reference')
    op.drop_table('import_jobs')
    op.drop_table('task_type', schema='core')
    op.drop_table('player_position', schema='core')
    op.drop_table('participation_status', schema='core')
    op.drop_table('member_role', schema='core')
    op.drop_table('game_status', schema='core')
    op.drop_table('game_action_type', schema='core')
    op.drop_table('event_type', schema='core')
    # ### end Alembic commands ###
