"""add_president_info_to_club

Revision ID: a0ac238150d0
Revises: ba6e1ca61423
Create Date: 2026-02-06 21:47:00.397359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0ac238150d0'
down_revision: Union[str, None] = 'ba6e1ca61423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('president_first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True), schema='reference')
    op.add_column('club', sa.Column('president_last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True), schema='reference')
    op.add_column('club', sa.Column('president_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True), schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'president_email', schema='reference')
    op.drop_column('club', 'president_last_name', schema='reference')
    op.drop_column('club', 'president_first_name', schema='reference')
    # ### end Alembic commands ###
