"""Add rating and motm fields

Revision ID: a5359d449f81
Revises: 7dc58c7f73dc
Create Date: 2026-02-19 17:39:40.040067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5359d449f81'
down_revision: Union[str, None] = '7dc58c7f73dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'),
               schema='core')
    op.alter_column('event', 'lineup_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='core')
    op.add_column('event_participation', sa.Column('rating', sa.Float(), nullable=True), schema='core')
    op.add_column('event_participation', sa.Column('motm_votes', sa.Integer(), nullable=False, server_default=sa.text('0')), schema='core')
    op.alter_column('formation', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True,
               schema='core')
    op.alter_column('formation_position', 'formation_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='core')
    op.alter_column('formation_position', 'role',
               existing_type=sa.CHAR(length=1),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1),
               nullable=False,
               schema='core')
    op.alter_column('formation_position', 'coord_x',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               nullable=False,
               schema='core')
    op.alter_column('formation_position', 'coord_y',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               nullable=False,
               schema='core')
    op.alter_column('formation_position', 'position_label',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='core')
    op.alter_column('formation_position', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'),
               schema='core')
    op.drop_constraint(op.f('formation_position_formation_id_coord_x_coord_y_key'), 'formation_position', schema='core', type_='unique')
    op.create_unique_constraint('uq_fmt_pos_coords', 'formation_position', ['formation_id', 'coord_x', 'coord_y'], schema='core')
    op.create_foreign_key(None, 'match_lineup', 'formation_position', ['position_id'], ['id'], source_schema='core', referent_schema='core')
    op.create_foreign_key(None, 'match_lineup', 'formation', ['formation_id'], ['id'], source_schema='core', referent_schema='core')
    op.alter_column('game', 'is_chat_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'is_chat_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='reference')
    op.drop_constraint(None, 'match_lineup', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'match_lineup', schema='core', type_='foreignkey')
    op.drop_constraint('uq_fmt_pos_coords', 'formation_position', schema='core', type_='unique')
    op.create_unique_constraint(op.f('formation_position_formation_id_coord_x_coord_y_key'), 'formation_position', ['formation_id', 'coord_x', 'coord_y'], schema='core', postgresql_nulls_not_distinct=False)
    op.alter_column('formation_position', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'),
               schema='core')
    op.alter_column('formation_position', 'position_label',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               schema='core')
    op.alter_column('formation_position', 'coord_y',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               schema='core')
    op.alter_column('formation_position', 'coord_x',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               schema='core')
    op.alter_column('formation_position', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1),
               type_=sa.CHAR(length=1),
               nullable=True,
               schema='core')
    op.alter_column('formation_position', 'formation_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='core')
    op.alter_column('formation', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='core')
    op.drop_column('event_participation', 'motm_votes', schema='core')
    op.drop_column('event_participation', 'rating', schema='core')
    op.alter_column('event', 'lineup_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='core')
    op.alter_column('event', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'),
               schema='core')
    # ### end Alembic commands ###
