"""make_team_tenant_id_nullable

Revision ID: addccb30aca0
Revises: a0ac238150d0
Create Date: 2026-02-09 21:03:22.686455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'addccb30aca0'
down_revision: Union[str, None] = 'a0ac238150d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('game_id', sa.Uuid(), nullable=True), schema='core')
    op.create_foreign_key(None, 'event', 'game', ['game_id'], ['id'], source_schema='core', referent_schema='reference')
    op.add_column('game', sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True), schema='reference')
    op.add_column('game', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True), schema='reference')
    op.add_column('game', sa.Column('phase_number', sa.Integer(), nullable=True), schema='reference')
    op.add_column('game', sa.Column('phase_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True), schema='reference')
    op.add_column('game', sa.Column('poule_stage_number', sa.Integer(), nullable=True), schema='reference')
    op.add_column('game', sa.Column('poule_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True), schema='reference')
    op.alter_column('team', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='reference')
    op.drop_column('game', 'poule_name', schema='reference')
    op.drop_column('game', 'poule_stage_number', schema='reference')
    op.drop_column('game', 'phase_name', schema='reference')
    op.drop_column('game', 'phase_number', schema='reference')
    op.drop_column('game', 'city', schema='reference')
    op.drop_column('game', 'zip_code', schema='reference')
    op.drop_constraint(None, 'event', schema='core', type_='foreignkey')
    op.drop_column('event', 'game_id', schema='core')
    # ### end Alembic commands ###
