"""Add code column to player_position

Revision ID: ba6e1ca61423
Revises: 0fc65e842da3
Create Date: 2026-02-02 13:16:10.031239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba6e1ca61423'
down_revision: Union[str, None] = '0fc65e842da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_position', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_position', 'code', schema='core')
    # ### end Alembic commands ###
