"""fix_saas_user_constraint

Revision ID: e5104d425da0
Revises: e5855de1af6d
Create Date: 2026-01-24 11:31:54.456591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5104d425da0'
down_revision: Union[str, None] = 'e5855de1af6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_full_name_key'), 'users', schema='saas', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_full_name_key'), 'users', ['full_name'], schema='saas', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
