"""add_club_id_to_game_and_team

Revision ID: f30bf54b6c7a
Revises: 8ebf8d877573
Create Date: 2026-02-01 21:01:48.921779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f30bf54b6c7a'
down_revision: Union[str, None] = '8ebf8d877573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('home_club_id', sa.Uuid(), nullable=True), schema='reference')
    op.add_column('game', sa.Column('away_club_id', sa.Uuid(), nullable=True), schema='reference')
    op.create_foreign_key(None, 'game', 'club', ['away_club_id'], ['id'], source_schema='reference', referent_schema='reference')
    op.create_foreign_key(None, 'game', 'club', ['home_club_id'], ['id'], source_schema='reference', referent_schema='reference')
    op.add_column('team', sa.Column('club_id', sa.Uuid(), nullable=True), schema='reference')
    op.create_foreign_key(None, 'team', 'club', ['club_id'], ['id'], source_schema='reference', referent_schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', schema='reference', type_='foreignkey')
    op.drop_column('team', 'club_id', schema='reference')
    op.drop_constraint(None, 'game', schema='reference', type_='foreignkey')
    op.drop_constraint(None, 'game', schema='reference', type_='foreignkey')
    op.drop_column('game', 'away_club_id', schema='reference')
    op.drop_column('game', 'home_club_id', schema='reference')
    # ### end Alembic commands ###
