"""update game unique constraint

Revision ID: f32da16dc0cb
Revises: f30bf54b6c7a
Create Date: 2026-02-01 23:21:34.402447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f32da16dc0cb'
down_revision: Union[str, None] = 'f30bf54b6c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_game_data_hash'), 'game', schema='reference', type_='unique')
    op.create_unique_constraint('uq_game_data_hash_tenant', 'game', ['data_hash', 'tenant_id'], schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_game_data_hash_tenant', 'game', schema='reference', type_='unique')
    op.create_unique_constraint(op.f('uq_game_data_hash'), 'game', ['data_hash'], schema='reference', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
